project:
  type: website
  output-dir: docs

website:
  title: "The Roaming Sophie"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Destinations.qmd
      - Stories.qmd
      - BucketList.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

